language: python

python:
  - 3.5

install:
  - pip install sphinx sphinx_rtd_theme

script:
  - cd docs
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/html/
  on:
    branch: master