name: generate-docs

on:
  push:
    branches:
      - 'hs649/gh-actions'

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sphinx_rtd_theme
        run: |
          python -m pip install --upgrade pip
          pip install sphinx_rtd_theme
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $GITHUB_TOKEN
          publish_dir: docs/build/html/
          publish_branch: mock-gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'