name: generate-docs

on:
  push:
    branches:
      - 'hs649/gh-actions'

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Sphinx and sphinx_rtd_theme
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx
          pip install sphinx_rtd_theme

      - name: Build Sphinx documentation
        run: |
          # cd docs
          # make html
          pwd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          publish_branch: mock-gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'