name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go to docs folder
        run: cd docs
      - name: Print "hello world" 
        run: echo hello world